- name: gathering facts
  hosts: local
  connection: local
  tasks:
  - name: print facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"



- name: generate stats
  hosts: local
  connections: local
  tasks:
    - name: print facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"